# Generated by Django 4.2.29 on 2026-04-03 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0001_program_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmilestone",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Accountable person for this milestone (shown on program view).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_milestones_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
