# Generated by Django 4.2.29 on 2026-04-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0001_program_management"),
        ("projects", "0005_milestone_tranche_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a long-running program; leave blank for standalone projects.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="programs.program",
            ),
        ),
    ]
