#!/usr/bin/env python3
"""
CSV Generator — Creates synthetic customer data files for load testing

Generates realistic CSV files matching the DC2_S vertical schema (11-file consolidated):
  - accounts.csv: Account records with company names, tiers, ARR
  - kpi_measurements.csv: KPIs × N accounts × M months of measurements
  - products.csv: Product/service records per account
  - contacts.csv: Customer contacts (CSMs, executives, technical leads)
  - enhanced_qualitative_signals.csv: Scenario-aware signals with optional graph metadata

Note: profiles.csv and customers.csv have been consolidated into
account_business_profiles.csv (generated by the context graph pipeline).

Uses Faker for realistic company/person names.
Convention: account_id = customer_id × 1000 + offset (1-based)
CSV names MUST match onboarding API expectations (FILE_TYPES in onboarding_api_v2_config_aware.py)
"""

import csv
import io
import random
import math
import logging
import uuid as uuid_mod
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from pathlib import Path

try:
    from faker import Faker
    fake = Faker()
except ImportError:
    fake = None

logger = logging.getLogger(__name__)

# DC2_S KPI definitions loaded from shared catalog (single source of truth)
try:
    from catalog_loader import get_kpi_list_for_load_driver
    DC2S_KPIS = get_kpi_list_for_load_driver()
    logger.info(f"Loaded {len(DC2S_KPIS)} KPIs from catalog JSON")
except Exception as e:
    logger.warning(f"Failed to load catalog: {e}, using minimal fallback")
    DC2S_KPIS = [
        {'code': f'{p}-KPI{i}', 'name': f'{p}-KPI{i}', 'pillar': p, 'weight': 0.33, 'unit': '%'}
        for p in ['P1', 'P2', 'P3', 'P4', 'P5'] for i in range(1, 4)
    ]

# Account tiers and their ARR ranges
TIERS = {
    'Enterprise': (500_000, 5_000_000),
    'Mid-Market': (100_000, 499_999),
    'SMB': (10_000, 99_999),
}

TIER_DISTRIBUTION = {
    'Enterprise': 0.20,
    'Mid-Market': 0.50,
    'SMB': 0.30,
}

# Products commonly associated with DC2_S (data center) accounts
DC2S_PRODUCTS = [
    'GPU Compute Cluster',
    'AI Training Platform',
    'Inference Engine',
    'Data Lake Storage',
    'Edge Deployment Kit',
    'Network Fabric Controller',
    'Cooling Management System',
    'Power Distribution Unit',
    'Security Gateway',
    'Monitoring Dashboard',
]

INDUSTRIES = [
    'Technology', 'Financial Services', 'Healthcare',
    'Manufacturing', 'Retail', 'Energy',
    'Telecommunications', 'Government', 'Education',
    'Media & Entertainment'
]

REGIONS = ['North America', 'EMEA', 'APAC', 'LATAM']

CSM_MANAGERS = ['Sam Rivera', 'Alex Chen', 'Jordan Blake']

CHAMPION_TITLES = [
    'VP Engineering', 'CTO', 'Director of AI',
    'Head of Infrastructure', 'VP Data Science',
    'Director of IT Operations', 'Chief Data Officer',
]


class CSVGenerator:
    """
    Generates synthetic CSV files for load testing the CS Pulse platform

    Usage:
        gen = CSVGenerator(customer_id=1, num_accounts=50, seed=42)
        gen.generate_all('/tmp/customer1_data/')

    Or get CSV content as strings:
        accounts_csv = gen.generate_accounts_csv()
        kpi_csv = gen.generate_kpi_csv(months=3)
    """

    def __init__(
        self,
        customer_id: int = 1,
        num_accounts: int = 50,
        seed: int = None
    ):
        self.customer_id = customer_id
        self.num_accounts = num_accounts
        self.account_base = customer_id * 1000 + 1

        if seed is not None:
            random.seed(seed)
            if fake:
                Faker.seed(seed)

    def generate_all(self, output_dir: str) -> Dict[str, str]:
        """
        Generate all CSV files to the specified directory

        Returns:
            Dict of filename → file path
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        files = {}

        accounts_csv = self.generate_accounts_csv()
        accounts_file = output_path / 'accounts.csv'
        accounts_file.write_text(accounts_csv)
        files['accounts.csv'] = str(accounts_file)

        kpi_csv = self.generate_kpi_csv(months=3)
        kpi_file = output_path / 'kpi_measurements.csv'
        kpi_file.write_text(kpi_csv)
        files['kpi_measurements.csv'] = str(kpi_file)

        products_csv = self.generate_products_csv()
        products_file = output_path / 'products.csv'
        products_file.write_text(products_csv)
        files['products.csv'] = str(products_file)

        contacts_csv = self.generate_contacts_csv()
        contacts_file = output_path / 'contacts.csv'
        contacts_file.write_text(contacts_csv)
        files['contacts.csv'] = str(contacts_file)

        # Enhanced qualitative signals (consolidated from qualitative_signals + graph metadata)
        signals_csv = self.generate_qualitative_signals_csv()
        signals_file = output_path / 'enhanced_qualitative_signals.csv'
        signals_file.write_text(signals_csv)
        files['enhanced_qualitative_signals.csv'] = str(signals_file)

        # Note: profiles.csv removed — merged into account_business_profiles
        # (generated by context graph pipeline)

        logger.info(f"Generated {len(files)} CSV files in {output_dir}")
        for name, path in files.items():
            logger.info(f"  {name}: {path}")

        return files

    def generate_accounts_csv(self) -> str:
        """Generate accounts.csv with N realistic account records.

        Columns aligned with backend generate_synthetic_customer_data.py
        and onboarding_api_v2_config_aware.py expectations.
        """
        output = io.StringIO()
        writer = csv.writer(output)

        # Header — matches backend generator + onboarding API expectations
        # Includes CSM/champion columns (previously in profiles.csv, now consolidated)
        writer.writerow([
            'account_id', 'customer_id', 'account_name', 'industry', 'region',
            'vertical', 'tier', 'arr', 'revenue', 'contract_start', 'contract_end',
            'renewal_date', 'csm_name', 'csm_email', 'account_status', 'uuid',
            'csm_manager', 'executive_sponsor',
            'primary_champion_name', 'primary_champion_title',
            'primary_champion_email', 'primary_champion_engagement_score'
        ])

        # Store generated accounts for use by signals/profiles generators
        self._accounts = []

        for i in range(self.num_accounts):
            account_id = self.account_base + i
            tier = self._pick_tier()
            arr_min, arr_max = TIERS[tier]
            arr = round(random.uniform(arr_min, arr_max), 2)

            if fake:
                company = fake.company()
                csm_name = fake.name()
                csm_email = fake.email()
                champion_name = fake.name()
                champion_email = fake.email()
                exec_sponsor = fake.name()
            else:
                company = f"DataCenter-Corp-{account_id}"
                csm_name = f"CSM-{account_id}"
                csm_email = f"csm{account_id}@example.com"
                champion_name = f"Champion-{account_id}"
                champion_email = f"champion@account{account_id}.com"
                exec_sponsor = f"ExecSponsor-{account_id}"

            csm_manager = random.choice(CSM_MANAGERS)
            champion_title = random.choice(CHAMPION_TITLES)
            champion_engagement = round(random.uniform(50, 95), 1)

            contract_start = datetime(2024, 1, 1) + timedelta(days=random.randint(0, 180))
            contract_end = contract_start + timedelta(days=365)
            renewal_date = contract_end - timedelta(days=30)
            status = random.choice(['active', 'active', 'active', 'at_risk', 'churning'])

            # Assign scenario based on account index (matches backend pattern)
            scenarios = ['improving', 'stable_healthy', 'declining']
            scenario = scenarios[i % 3]

            acct = {
                'account_id': account_id,
                'account_name': company,
                'csm_name': csm_name,
                'arr': arr,
                'status': status,
                'scenario': scenario,
            }
            self._accounts.append(acct)

            writer.writerow([
                account_id,
                self.customer_id,
                company,
                random.choice(INDUSTRIES),
                random.choice(REGIONS),
                'dc2_s',
                tier,
                arr,
                arr,  # revenue = arr for consistency
                contract_start.strftime('%Y-%m-%d'),
                contract_end.strftime('%Y-%m-%d'),
                renewal_date.strftime('%Y-%m-%d'),
                csm_name,
                csm_email,
                status,
                f'dc_acct_{uuid_mod.uuid4().hex[:12]}',
                csm_manager,
                exec_sponsor,
                champion_name,
                champion_title,
                champion_email,
                champion_engagement,
            ])

        return output.getvalue()

    def generate_kpi_csv(self, months: int = 3) -> str:
        """
        Generate kpi_measurements.csv with KPIs × N accounts × M months

        Column names aligned with backend generator and onboarding API.

        Args:
            months: Number of months of data (default 3)
        """
        output = io.StringIO()
        writer = csv.writer(output)

        # Header — matches backend generator column names
        writer.writerow([
            'account_id', 'kpi_code', 'kpi_name', 'pillar',
            'measured_at', 'value', 'target', 'weight', 'unit', 'status'
        ])

        base_date = datetime(2024, 10, 1)  # Start from Oct 2024

        for i in range(self.num_accounts):
            account_id = self.account_base + i

            for month_offset in range(months):
                measured_at = (base_date + timedelta(days=30 * month_offset)).strftime('%Y-%m-%d')

                for kpi in DC2S_KPIS:
                    target = self._get_kpi_target(kpi['code'])
                    value = self._generate_kpi_value(kpi['code'], target, month_offset)
                    status = self._classify_kpi_status(kpi['code'], value)

                    writer.writerow([
                        account_id,
                        kpi['code'],
                        kpi['name'],
                        kpi['pillar'],
                        measured_at,
                        round(value, 2),
                        round(target, 2),
                        kpi['weight'],
                        kpi['unit'],
                        status,
                    ])

        return output.getvalue()

    def generate_products_csv(self) -> str:
        """Generate products.csv with 1-4 products per account"""
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            'account_id', 'product_name', 'product_category',
            'quantity', 'unit_price', 'deployment_date', 'status'
        ])

        for i in range(self.num_accounts):
            account_id = self.account_base + i
            num_products = random.randint(1, 4)
            products = random.sample(DC2S_PRODUCTS, min(num_products, len(DC2S_PRODUCTS)))

            for product in products:
                deploy_date = datetime(2024, 1, 1) + timedelta(days=random.randint(0, 365))
                writer.writerow([
                    account_id,
                    product,
                    self._product_category(product),
                    random.randint(1, 100),
                    round(random.uniform(1000, 50000), 2),
                    deploy_date.strftime('%Y-%m-%d'),
                    random.choice(['active', 'active', 'active', 'provisioning', 'decommissioned']),
                ])

        return output.getvalue()

    def generate_contacts_csv(self) -> str:
        """Generate contacts.csv with 2-5 contacts per account"""
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            'account_id', 'contact_name', 'contact_email',
            'role', 'department', 'is_primary'
        ])

        roles = [
            'VP Engineering', 'CTO', 'Director IT',
            'Data Center Manager', 'Cloud Architect',
            'Infrastructure Lead', 'DevOps Manager',
            'Procurement Manager', 'CFO'
        ]

        departments = [
            'Engineering', 'IT', 'Operations',
            'Infrastructure', 'Finance', 'Executive'
        ]

        for i in range(self.num_accounts):
            account_id = self.account_base + i
            num_contacts = random.randint(2, 5)

            for j in range(num_contacts):
                if fake:
                    name = fake.name()
                    email = fake.email()
                else:
                    name = f"Contact-{account_id}-{j}"
                    email = f"contact{j}@account{account_id}.com"

                writer.writerow([
                    account_id,
                    name,
                    email,
                    random.choice(roles),
                    random.choice(departments),
                    'true' if j == 0 else 'false',  # First contact is primary
                ])

        return output.getvalue()

    def _pick_tier(self) -> str:
        """Pick tier based on distribution"""
        return random.choices(
            list(TIER_DISTRIBUTION.keys()),
            weights=list(TIER_DISTRIBUTION.values()),
            k=1
        )[0]

    def _get_kpi_target(self, kpi_code: str) -> float:
        """Get realistic target value for a KPI code"""
        targets = {
            'P3-KPI1': 85.0,   # GPU Utilization %
            'P3-KPI2': 12.0,   # Deployments/month
            'P3-KPI3': 50.0,   # Latency ms (lower is better, but stored as score)
            'P4-KPI1': 80.0,   # Partner engagement score
            'P4-KPI2': 30.0,   # Channel revenue %
            'P4-KPI3': 4.0,    # Certification level (1-5)
            'P1-KPI1': 99.9,   # Uptime %
            'P1-KPI2': 95.0,   # Deploy success %
            'P1-KPI3': 14.0,   # Days to first workload (lower better)
            'P5-KPI1': 75.0,   # Capacity util %
            'P5-KPI2': 500000, # Pipeline $
            'P5-KPI3': 25.0,   # Upsell conversion %
            'P2-KPI1': 98.0,   # SLA compliance %
            'P2-KPI2': 4.0,    # MTTR hours (lower better)
            'P2-KPI3': 90.0,   # Incident resolution %
        }
        return targets.get(kpi_code, 85.0)

    def _generate_kpi_value(self, kpi_code: str, target: float, month: int) -> float:
        """Generate a realistic KPI value with some variance"""
        # Base variance: ±20% around target
        variance = target * 0.20
        value = target + random.gauss(0, variance * 0.5)

        # Month trend: slight improvement over time
        value += month * target * 0.01

        # Ensure reasonable bounds
        if kpi_code in ('P1-KPI1', 'P2-KPI1'):  # Uptime/SLA should be high
            value = max(90.0, min(100.0, value))
        elif kpi_code in ('P3-KPI3', 'P1-KPI3', 'P2-KPI2'):  # Lower is better
            value = max(1.0, value)
        elif kpi_code == 'P4-KPI3':  # Certification level 1-5
            value = max(1.0, min(5.0, value))
        elif kpi_code == 'P5-KPI2':  # Pipeline value (dollar amount)
            value = max(0, value)
        else:
            value = max(0, min(100, value))

        return value

    def generate_qualitative_signals_csv(self, months: int = 3) -> str:
        """Generate enhanced_qualitative_signals.csv — scenario-aware signals
        with optional graph metadata columns.

        Output filename: enhanced_qualitative_signals.csv (consolidated from
        the old qualitative_signals.csv with added context graph columns).
        Matches backend generator column names for onboarding API compatibility.
        Must call generate_accounts_csv() first to populate self._accounts.
        """
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            'signal_id', 'account_id', 'signal_date', 'signal_type',
            'content', 'sentiment', 'sentiment_score',
            'arc_id', 'story_phase', 'linked_node_id'
        ])

        signal_types = ['customer_feedback', 'meeting', 'milestone', 'health_check', 'incident']

        # Scenario-aware signal templates (matching backend generator pattern)
        templates = {
            'improving': {
                'positive': [
                    'GPU utilization continues to increase month over month',
                    'Successful deployment of new AI training workloads',
                    'Executive sponsor very engaged in QBR',
                    'Customer exploring expansion into inference workloads',
                ],
                'neutral': [
                    'Routine maintenance completed on schedule',
                    'Standard QBR conducted with all stakeholders',
                ],
            },
            'stable_healthy': {
                'positive': [
                    'Consistent uptime metrics exceeding SLA',
                    'Partner relationship remains strong',
                ],
                'neutral': [
                    'No significant changes in workload patterns',
                    'Standard operational review completed',
                    'Renewal discussion progressing normally',
                ],
            },
            'declining': {
                'negative': [
                    'Increase in support ticket volume observed',
                    'Executive sponsor missed scheduled QBR',
                    'GPU utilization trending downward',
                    'Competitor mentioned in stakeholder conversation',
                ],
                'neutral': [
                    'Awaiting response on renewal terms',
                    'Budget review flagged by customer CFO',
                ],
            },
        }

        base_date = datetime(2024, 10, 1)
        counter = 0

        accounts = getattr(self, '_accounts', [])
        if not accounts:
            # Fallback if accounts not generated yet
            accounts = [{'account_id': self.account_base + i, 'scenario': ['improving', 'stable_healthy', 'declining'][i % 3]}
                        for i in range(self.num_accounts)]

        for acct in accounts:
            account_id = acct['account_id']
            scenario = acct.get('scenario', 'stable_healthy')
            scenario_templates = templates.get(scenario, templates['stable_healthy'])

            for month_offset in range(months):
                # 2-3 signals per account per month
                num_signals = random.randint(2, 3)
                for _ in range(num_signals):
                    counter += 1
                    signal_date = base_date + timedelta(days=30 * month_offset + random.randint(0, 29))

                    # Pick sentiment based on scenario
                    if scenario == 'improving':
                        sentiment = random.choices(['positive', 'neutral'], weights=[0.7, 0.3])[0]
                    elif scenario == 'declining':
                        sentiment = random.choices(['negative', 'neutral'], weights=[0.6, 0.4])[0]
                    else:
                        sentiment = random.choices(['positive', 'neutral'], weights=[0.5, 0.5])[0]

                    content_pool = scenario_templates.get(sentiment, scenario_templates.get('neutral', ['No update']))
                    content = random.choice(content_pool)

                    sentiment_scores = {'positive': round(random.uniform(0.5, 0.95), 2),
                                       'neutral': round(random.uniform(0.0, 0.3), 2),
                                       'negative': round(random.uniform(-0.9, -0.3), 2)}

                    writer.writerow([
                        f'sig_{account_id}_{counter}',
                        account_id,
                        signal_date.strftime('%Y-%m-%d'),
                        random.choice(signal_types),
                        content,
                        sentiment,
                        sentiment_scores[sentiment],
                        '',   # arc_id — populated by context graph pipeline
                        '',   # story_phase — populated by context graph pipeline
                        '',   # linked_node_id — populated by context graph pipeline
                    ])

        return output.getvalue()

    def _classify_kpi_status(self, kpi_code: str, value: float) -> str:
        """Classify KPI value as healthy/risk/critical using health thresholds.

        Uses simplified threshold logic consistent with backend score_calculator.py.
        For lower-is-better KPIs, lower values are healthier.
        """
        # Lower-is-better KPIs (time, latency, failure rates)
        lower_is_better = {'P3-KPI3', 'P1-KPI3', 'P2-KPI2',
                          'P1-KPI1', 'P1-KPI4', 'P1-KPI5',
                          'P2-KPI1', 'P2-KPI6', 'P2-KPI7',
                          'P3-KPI3', 'P3-KPI4', 'P4-KPI4'}

        if kpi_code in lower_is_better:
            # For lower-is-better: score is inversely related
            # Approximate: if value <= target → healthy, up to 1.5x target → risk, above → critical
            target = self._get_kpi_target(kpi_code)
            if target > 0:
                ratio = value / target
                if ratio <= 1.0:
                    return 'healthy'
                elif ratio <= 1.5:
                    return 'risk'
                else:
                    return 'critical'
            return 'healthy'
        else:
            # Higher-is-better: normalize to 0-100 scale
            # Use health thresholds: >=70 healthy, 50-69 risk, <50 critical
            target = self._get_kpi_target(kpi_code)
            if target > 0:
                score = min(100, (value / target) * 100)
            else:
                score = 50
            if score >= 70:
                return 'healthy'
            elif score >= 50:
                return 'risk'
            else:
                return 'critical'

    def _product_category(self, product_name: str) -> str:
        """Map product name to category"""
        categories = {
            'GPU': 'Compute',
            'AI': 'AI/ML',
            'Inference': 'AI/ML',
            'Data Lake': 'Storage',
            'Edge': 'Edge',
            'Network': 'Networking',
            'Cooling': 'Facilities',
            'Power': 'Facilities',
            'Security': 'Security',
            'Monitoring': 'Observability',
        }
        for keyword, category in categories.items():
            if keyword in product_name:
                return category
        return 'Other'


def main():
    """CLI entry point for standalone CSV generation"""
    import argparse

    parser = argparse.ArgumentParser(description='Generate synthetic CSV data for CS Pulse load testing')
    parser.add_argument('--customer-id', type=int, default=1, help='Customer ID (default: 1)')
    parser.add_argument('--num-accounts', type=int, default=50, help='Number of accounts (default: 50)')
    parser.add_argument('--months', type=int, default=3, help='Months of KPI data (default: 3)')
    parser.add_argument('--output-dir', default='./generated_data', help='Output directory')
    parser.add_argument('--seed', type=int, default=42, help='Random seed for reproducibility')

    args = parser.parse_args()

    gen = CSVGenerator(
        customer_id=args.customer_id,
        num_accounts=args.num_accounts,
        seed=args.seed
    )
    files = gen.generate_all(args.output_dir)

    print(f"\nGenerated {len(files)} files:")
    for name, path in files.items():
        print(f"  {name}: {path}")


if __name__ == '__main__':
    main()
