"""Initial migration

Revision ID: ef4732fc8211
Revises: 
Create Date: 2025-07-12 15:00:19.412266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4732fc8211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('kpi_uploads',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('raw_excel', sa.LargeBinary(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('kpis',
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('health_score_component', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('source_review', sa.String(), nullable=True),
    sa.Column('kpi_parameter', sa.String(), nullable=True),
    sa.Column('impact_level', sa.String(), nullable=True),
    sa.Column('measurement_frequency', sa.String(), nullable=True),
    sa.Column('last_edited_by', sa.Integer(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['kpi_uploads.upload_id'], ),
    sa.PrimaryKeyConstraint('kpi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpis')
    op.drop_table('kpi_uploads')
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
