#!/usr/bin/env python3
"""
Onboarding Agent — AI-Powered Customer Activation for First 30-90 Days
=======================================================================
Dedicated agent for the new-customer lifecycle.  Responsibilities:

  1. Analyse newly loaded customer data (industry, account count, KPI patterns)
  2. Generate a tailored **activation plan** (priority accounts, recommended playbooks)
  3. Set TTFV (Time to First Value) tracking baseline
  4. Auto-trigger Activation-Blitz playbook where appropriate
  5. Graduate account to Signal Analyst steady-state monitoring after TTFV

Provider-agnostic: works with OpenAI GPT-4o or Anthropic Claude.

Reuses:
  - AgentToolRegistry  (power_of_1_calc, health_score_calc, memory_remember, …)
  - AgentMemoryManager (MemoryScope.SHARED for cross-agent intelligence)
  - create_signal_analyst_agent() factory for LLM provider selection
  - CircuitBreaker from utils/; cost tracking via utils.llm_budget_controller.record_usage
"""

import json
import os
import sys
import time
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

# Add parent directory for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from utils.error_handling import CircuitBreaker
from utils.logging_config import initialize_logging
from utils.llm_budget_controller import record_usage as _llm_record_usage
from sqlalchemy import create_engine, text

logger = initialize_logging()


# ============================================================
# DATA CLASSES
# ============================================================

@dataclass
class ActivationPlanEntry:
    """A single account in the activation plan."""
    account_id: str
    account_name: str
    priority: str          # high / medium / low
    risk_level: str        # at_risk / healthy / expanding
    recommended_playbooks: List[str]
    ttfv_target_days: int  # Target days to first value
    rationale: str


@dataclass
class ActivationPlan:
    """Full activation plan generated by the Onboarding Agent."""
    customer_id: int
    customer_name: str
    industry: str
    total_accounts: int
    plan_entries: List[ActivationPlanEntry]
    global_recommendations: List[str]
    ttfv_baseline: Dict[str, Any]
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    provider_used: str = "openai"
    generation_ms: int = 0


@dataclass
class TTFVStatus:
    """Time to First Value tracking for an account."""
    account_id: str
    onboarded_at: str
    ttfv_target_days: int
    current_day: int
    activation_score: float   # 0.0–1.0
    milestones_hit: List[str]
    is_graduated: bool = False
    graduated_at: Optional[str] = None


# ============================================================
# PROMPTS
# ============================================================

ONBOARDING_SYSTEM_PROMPT = """You are an expert Customer Success Onboarding Specialist AI.

Your role is to analyse a newly onboarded customer's data and create an activation plan
that maximises Time to First Value (TTFV).

Key principles:
1. **Prioritise at-risk accounts** — accounts showing early warning signals should get
   immediate attention via the activation-blitz playbook.
2. **Industry-aware recommendations** — adapt advice to the customer's industry vertical.
3. **Quantify impact** — estimate days-to-value and expected outcomes.
4. **Specific playbooks** — map each recommendation to a known playbook
   (activation-blitz, voc-sprint, qbr-cadence, sla-stabilizer, expansion-play).
5. **Graduation criteria** — define clear metrics for when an account moves from
   onboarding to steady-state monitoring.

Available playbooks:
- activation-blitz: Rapid adoption & engagement program (first 30 days)
- voc-sprint: Voice-of-Customer deep-dive (NPS/CSAT/sentiment focus)
- qbr-cadence: Quarterly Business Review cadence setup
- sla-stabilizer: SLA/support metric stabilization
- expansion-play: Upsell/cross-sell motion
"""

ONBOARDING_USER_PROMPT_TEMPLATE = """Analyse this newly onboarded customer and create an activation plan.

## Customer Info
- Customer ID: {customer_id}
- Customer Name: {customer_name}
- Industry: {industry}
- Onboarding Mode: {onboarding_mode}
- Total Accounts: {num_accounts}

## Account Summary
{account_summaries}

## KPI Snapshot (first data load)
{kpi_snapshot}

## Instructions
Return a JSON object with this exact structure:
{{
  "plan_entries": [
    {{
      "account_id": "<account ID>",
      "account_name": "<name>",
      "priority": "high|medium|low",
      "risk_level": "at_risk|healthy|expanding",
      "recommended_playbooks": ["activation-blitz", ...],
      "ttfv_target_days": <integer>,
      "rationale": "<2-3 sentence explanation>"
    }}
  ],
  "global_recommendations": [
    "<recommendation 1>",
    "<recommendation 2>"
  ],
  "ttfv_baseline": {{
    "avg_target_days": <integer>,
    "key_milestones": ["first login", "data upload", "dashboard viewed", "action taken"],
    "graduation_criteria": "<description of when accounts are ready for steady-state>"
  }}
}}

Return ONLY the JSON object. No markdown, no explanation outside the JSON.
"""


# ============================================================
# ONBOARDING AGENT
# ============================================================

class OnboardingAgent:
    """
    AI agent for new customer lifecycle (first 30-90 days).

    Owns TTFV metric.  Auto-triggers activation-blitz playbook.
    Graduates customer to Signal Analyst for steady-state monitoring.
    """

    def __init__(
        self,
        customer_id: int,
        provider: str = "openai",
        model: Optional[str] = None,
    ):
        self.customer_id = customer_id
        self.provider = provider.lower()
        self.model = model

        # LLM client (lazy-init on first call)
        self._llm_client = None

        # Circuit breaker
        self.breaker = CircuitBreaker(failure_threshold=3, timeout=120)

        # Cost tracking centralized via utils.llm_budget_controller.record_usage.
        # Previous code called self.cost_tracker.track_usage() which does not
        # exist on CostTracker — the cost log was silently never written.
        # Migration to record_usage both consolidates AND fixes that bug.

        logger.info(
            f"OnboardingAgent initialised for customer {customer_id}",
            extra={"provider": self.provider, "model": self.model},
        )

    # ────────────────────────────────────────────────────────
    #  LLM initialisation (supports OpenAI + Anthropic)
    # ────────────────────────────────────────────────────────

    def _get_llm_client(self):
        """Lazy-initialise LLM client based on provider."""
        if self._llm_client is not None:
            return self._llm_client

        if self.provider in ("anthropic", "claude"):
            import anthropic
            key = os.getenv("ANTHROPIC_API_KEY")
            if not key:
                raise ValueError("ANTHROPIC_API_KEY required for Claude provider")
            self._llm_client = anthropic.Anthropic(api_key=key)
            self.model = self.model or "claude-sonnet-4-5-20250929"
        else:
            from openai import OpenAI
            key = os.getenv("OPENAI_API_KEY")
            if not key:
                raise ValueError("OPENAI_API_KEY required for OpenAI provider")
            self._llm_client = OpenAI(api_key=key)
            self.model = self.model or "gpt-4o"

        return self._llm_client

    # ────────────────────────────────────────────────────────
    #  Core: analyse new customer & create activation plan
    # ────────────────────────────────────────────────────────

    def analyze_new_customer(
        self,
        customer_name: str,
        industry: str,
        onboarding_mode: str,
        accounts: List[Dict[str, Any]],
        kpi_snapshot: Optional[Dict[str, Any]] = None,
    ) -> ActivationPlan:
        """
        LLM-powered analysis of newly onboarded customer.

        Args:
            customer_name:   Display name of customer
            industry:        Industry vertical (Technology, Healthcare, …)
            onboarding_mode: 'demo' or 'custom'
            accounts:        List of account dicts [{id, name, arr, …}, …]
            kpi_snapshot:    Optional dict with initial KPI metrics

        Returns:
            ActivationPlan with priority accounts, playbooks, TTFV targets.
        """
        start_time = time.time()
        logger.info(
            f"[OnboardingAgent] Analysing customer {self.customer_id} ({customer_name}), "
            f"{len(accounts)} accounts"
        )

        # Build account summary text
        account_lines = []
        for acct in accounts:
            acct_id = acct.get("id") or acct.get("account_id", "unknown")
            acct_name = acct.get("name") or acct.get("account_name", "Unknown")
            arr = acct.get("arr") or acct.get("annual_revenue", "N/A")
            account_lines.append(f"- {acct_id}: {acct_name} (ARR: {arr})")
        account_summary_text = "\n".join(account_lines) or "No account details available."

        # Build KPI snapshot text
        kpi_text = "No KPI data available yet (first load pending)."
        if kpi_snapshot:
            kpi_lines = []
            for key, val in kpi_snapshot.items():
                kpi_lines.append(f"- {key}: {val}")
            kpi_text = "\n".join(kpi_lines)

        # Build user prompt
        user_prompt = ONBOARDING_USER_PROMPT_TEMPLATE.format(
            customer_id=self.customer_id,
            customer_name=customer_name,
            industry=industry,
            onboarding_mode=onboarding_mode,
            num_accounts=len(accounts),
            account_summaries=account_summary_text,
            kpi_snapshot=kpi_text,
        )

        # Call LLM
        raw_response = self._call_llm(
            system_prompt=ONBOARDING_SYSTEM_PROMPT,
            user_prompt=user_prompt,
        )

        # Parse response
        plan = self._parse_activation_plan(
            raw_response, customer_name, industry, accounts
        )
        plan.provider_used = self.provider
        plan.generation_ms = int((time.time() - start_time) * 1000)

        # Store activation plan in agent memory
        self._store_plan_in_memory(plan)

        logger.info(
            f"[OnboardingAgent] Activation plan generated in {plan.generation_ms}ms, "
            f"{len(plan.plan_entries)} accounts prioritised"
        )
        return plan

    # ────────────────────────────────────────────────────────
    #  LLM call (OpenAI or Anthropic)
    # ────────────────────────────────────────────────────────

    def _call_llm(self, system_prompt: str, user_prompt: str) -> str:
        """Call the configured LLM provider and return raw text response."""
        if self.breaker.is_open():
            raise RuntimeError("OnboardingAgent circuit breaker is open — too many LLM failures")

        client = self._get_llm_client()

        try:
            if self.provider in ("anthropic", "claude"):
                response = client.messages.create(
                    model=self.model,
                    max_tokens=4096,
                    temperature=0.3,
                    system=system_prompt,
                    messages=[{"role": "user", "content": user_prompt}],
                )
                raw = response.content[0].text

                # Cost tracking
                _llm_record_usage(
                    customer_id=self.customer_id,
                    module='onboarding_agent',
                    tokens_in=response.usage.input_tokens,
                    tokens_out=response.usage.output_tokens,
                    model=self.model,
                    success=True,
                )

            else:
                # OpenAI
                response = client.chat.completions.create(
                    model=self.model,
                    temperature=0.3,
                    max_tokens=4096,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    response_format={"type": "json_object"},
                )
                raw = response.choices[0].message.content

                # Cost tracking
                _llm_record_usage(
                    customer_id=self.customer_id,
                    module='onboarding_agent',
                    tokens_in=response.usage.prompt_tokens,
                    tokens_out=response.usage.completion_tokens,
                    model=self.model,
                    success=True,
                )

            self.breaker.record_success()
            return raw

        except Exception as e:
            self.breaker.record_failure()
            logger.error(f"[OnboardingAgent] LLM call failed: {e}", exc_info=True)
            raise

    # ────────────────────────────────────────────────────────
    #  Parse activation plan from LLM response
    # ────────────────────────────────────────────────────────

    def _parse_activation_plan(
        self,
        raw_response: str,
        customer_name: str,
        industry: str,
        accounts: List[Dict],
    ) -> ActivationPlan:
        """Parse LLM JSON response into an ActivationPlan dataclass."""
        try:
            # Strip markdown code fences if present
            text = raw_response.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1] if "\n" in text else text[3:]
            if text.endswith("```"):
                text = text[:-3].strip()
            if text.startswith("json"):
                text = text[4:].strip()

            data = json.loads(text)
        except json.JSONDecodeError:
            logger.warning("[OnboardingAgent] Failed to parse LLM JSON — using rule-based fallback")
            return self._fallback_plan(customer_name, industry, accounts)

        # Build plan entries
        entries = []
        for entry_data in data.get("plan_entries", []):
            entries.append(ActivationPlanEntry(
                account_id=str(entry_data.get("account_id", "")),
                account_name=str(entry_data.get("account_name", "")),
                priority=entry_data.get("priority", "medium"),
                risk_level=entry_data.get("risk_level", "healthy"),
                recommended_playbooks=entry_data.get("recommended_playbooks", ["activation-blitz"]),
                ttfv_target_days=int(entry_data.get("ttfv_target_days", 30)),
                rationale=entry_data.get("rationale", ""),
            ))

        return ActivationPlan(
            customer_id=self.customer_id,
            customer_name=customer_name,
            industry=industry,
            total_accounts=len(accounts),
            plan_entries=entries,
            global_recommendations=data.get("global_recommendations", []),
            ttfv_baseline=data.get("ttfv_baseline", {
                "avg_target_days": 30,
                "key_milestones": ["first login", "data upload", "dashboard viewed"],
                "graduation_criteria": "Health score >= 70 for 2 consecutive weeks",
            }),
        )

    def _fallback_plan(
        self,
        customer_name: str,
        industry: str,
        accounts: List[Dict],
    ) -> ActivationPlan:
        """Rule-based fallback if LLM call fails."""
        entries = []
        for i, acct in enumerate(accounts):
            acct_id = str(acct.get("id") or acct.get("account_id", f"acct-{i}"))
            acct_name = acct.get("name") or acct.get("account_name", f"Account {i+1}")
            entries.append(ActivationPlanEntry(
                account_id=acct_id,
                account_name=acct_name,
                priority="high" if i == 0 else "medium",
                risk_level="healthy",
                recommended_playbooks=["activation-blitz"],
                ttfv_target_days=30,
                rationale=f"Default activation plan — {acct_name} assigned standard 30-day onboarding track.",
            ))

        return ActivationPlan(
            customer_id=self.customer_id,
            customer_name=customer_name,
            industry=industry,
            total_accounts=len(accounts),
            plan_entries=entries,
            global_recommendations=[
                "Schedule kickoff call with customer stakeholders",
                "Enable all core dashboards and configure alerts",
                f"Review {industry}-specific KPI benchmarks with the customer",
            ],
            ttfv_baseline={
                "avg_target_days": 30,
                "key_milestones": ["first login", "data upload", "dashboard viewed", "action taken"],
                "graduation_criteria": "Health score >= 70 for 2 consecutive weeks",
            },
        )

    # ────────────────────────────────────────────────────────
    #  Memory: store activation plan for cross-agent access
    # ────────────────────────────────────────────────────────

    def _store_plan_in_memory(self, plan: ActivationPlan) -> None:
        """Persist activation plan in agent memory (ENTITY + SHARED scope)."""
        try:
            from agent_memory import (
                get_memory_store, MemoryEntry, MemoryType, MemoryScope
            )
            store = get_memory_store()

            # Store full plan as ENTITY memory (customer-level)
            plan_json = json.dumps({
                "plan_entries": [asdict(e) for e in plan.plan_entries],
                "global_recommendations": plan.global_recommendations,
                "ttfv_baseline": plan.ttfv_baseline,
                "created_at": plan.created_at,
                "provider_used": plan.provider_used,
            })

            store.remember(MemoryEntry(
                memory_type=MemoryType.ENTITY,
                scope=MemoryScope.CUSTOMER,
                content=plan_json,
                customer_id=plan.customer_id,
                namespace="activation_plan",
                key=f"plan_{plan.customer_id}",
                metadata={
                    "industry": plan.industry,
                    "total_accounts": plan.total_accounts,
                    "generation_ms": plan.generation_ms,
                },
                importance=0.9,
            ))

            # Store summary in SHARED scope for Signal Analyst to read
            summary = (
                f"Customer {plan.customer_name} ({plan.industry}) onboarded with "
                f"{plan.total_accounts} accounts. "
                f"Priority accounts: {', '.join(e.account_id for e in plan.plan_entries if e.priority == 'high')}. "
                f"TTFV target: {plan.ttfv_baseline.get('avg_target_days', 30)} days."
            )
            store.remember(MemoryEntry(
                memory_type=MemoryType.EPISODIC,
                scope=MemoryScope.SHARED,
                content=summary,
                customer_id=plan.customer_id,
                namespace="customer_intelligence",
                key=f"onboarding_{plan.customer_id}",
                importance=0.85,
            ))

            logger.info(f"[OnboardingAgent] Stored activation plan in memory for customer {plan.customer_id}")

        except Exception as e:
            logger.warning(f"[OnboardingAgent] Failed to store plan in memory: {e}")

    # ────────────────────────────────────────────────────────
    #  TTFV: evaluate activation readiness
    # ────────────────────────────────────────────────────────

    def evaluate_activation_readiness(self, account_id: str) -> TTFVStatus:
        """
        Check if an account has achieved first value (TTFV metric).

        Queries KPI trends since onboarding, calculates activation score.
        """
        logger.info(f"[OnboardingAgent] Evaluating TTFV for account {account_id}")

        # Get onboarding date from memory
        onboarded_at = datetime.utcnow() - timedelta(days=30)  # Default
        try:
            from agent_memory import get_memory_store, MemoryType
            store = get_memory_store()
            plan_memories = store.recall(
                customer_id=self.customer_id,
                namespace="activation_plan",
                limit=1,
            )
            if plan_memories:
                plan_data = json.loads(plan_memories[0].content)
                if "created_at" in plan_data:
                    onboarded_at = datetime.fromisoformat(plan_data["created_at"])
        except Exception:
            pass

        days_since = (datetime.utcnow() - onboarded_at).days

        # Get target days from plan
        ttfv_target = 30
        try:
            from agent_memory import get_memory_store
            store = get_memory_store()
            plan_memories = store.recall(
                customer_id=self.customer_id,
                namespace="activation_plan",
                limit=1,
            )
            if plan_memories:
                plan_data = json.loads(plan_memories[0].content)
                for entry in plan_data.get("plan_entries", []):
                    if entry.get("account_id") == account_id:
                        ttfv_target = entry.get("ttfv_target_days", 30)
                        break
        except Exception:
            pass

        # Calculate activation score from DB data
        activation_score, milestones = self._calculate_activation_score(account_id)

        is_graduated = activation_score >= 0.7 and days_since >= 14
        graduated_at = datetime.utcnow().isoformat() if is_graduated else None

        return TTFVStatus(
            account_id=account_id,
            onboarded_at=onboarded_at.isoformat(),
            ttfv_target_days=ttfv_target,
            current_day=days_since,
            activation_score=activation_score,
            milestones_hit=milestones,
            is_graduated=is_graduated,
            graduated_at=graduated_at,
        )

    def _calculate_activation_score(self, account_id: str) -> tuple:
        """
        Calculate activation score (0.0–1.0) from actual KPI data.

        Returns (score, milestones_hit).
        """
        milestones = []
        score = 0.0

        try:
            db_url = os.getenv("DATABASE_URL")
            if not db_url:
                return 0.3, ["data_loaded"]

            engine = create_engine(db_url)
            with engine.connect() as conn:
                # Check if KPI data exists
                result = conn.execute(text(
                    "SELECT COUNT(*) FROM dc2s_kpis WHERE account_id = :aid AND customer_id = :cid"
                ), {"aid": account_id, "cid": self.customer_id})
                kpi_count = result.scalar() or 0

                if kpi_count > 0:
                    milestones.append("data_loaded")
                    score += 0.2

                # Check if health scores exist
                result = conn.execute(text(
                    "SELECT COUNT(*) FROM health_scores WHERE account_id = :aid AND customer_id = :cid"
                ), {"aid": account_id, "cid": self.customer_id})
                health_count = result.scalar() or 0

                if health_count > 0:
                    milestones.append("health_scores_calculated")
                    score += 0.2

                # Check latest health score value
                result = conn.execute(text("""
                    SELECT overall_score FROM health_scores
                    WHERE account_id = :aid AND customer_id = :cid
                    ORDER BY calculated_at DESC LIMIT 1
                """), {"aid": account_id, "cid": self.customer_id})
                row = result.fetchone()
                if row and row[0]:
                    try:
                        import utils.health_thresholds as _ht
                        _h_min, _a_min = _ht.healthy_min(), _ht.at_risk_min()
                    except ImportError:
                        _h_min, _a_min = 70, 50
                    if row[0] >= _h_min:
                        milestones.append("healthy_score")
                        score += 0.3
                    elif row[0] >= _a_min:
                        milestones.append("moderate_score")
                        score += 0.15

                # Check if any agent analysis has been done
                result = conn.execute(text(
                    "SELECT COUNT(*) FROM agent_memory WHERE account_id = :aid "
                    "AND customer_id = :cid AND namespace = 'analysis'"
                ), {"aid": account_id, "cid": self.customer_id})
                analysis_count = result.scalar() or 0

                if analysis_count > 0:
                    milestones.append("analysis_run")
                    score += 0.15

                # Check if journey data exists
                result = conn.execute(text(
                    "SELECT COUNT(*) FROM customer_journey WHERE account_id = :aid AND customer_id = :cid"
                ), {"aid": account_id, "cid": self.customer_id})
                journey_count = result.scalar() or 0

                if journey_count > 0:
                    milestones.append("journey_generated")
                    score += 0.15

        except Exception as e:
            logger.warning(f"[OnboardingAgent] Error calculating activation score: {e}")
            milestones.append("data_loaded")
            score = 0.3

        return min(score, 1.0), milestones

    # ────────────────────────────────────────────────────────
    #  Graduate account to steady-state Signal Analyst
    # ────────────────────────────────────────────────────────

    def graduate_to_steady_state(self, account_id: str) -> Dict[str, Any]:
        """
        Hand off account from onboarding agent to Signal Analyst.

        Stores handoff context in shared memory and publishes graduation event.
        """
        logger.info(f"[OnboardingAgent] Graduating account {account_id} to steady-state")

        # Evaluate current readiness
        status = self.evaluate_activation_readiness(account_id)

        # Store graduation in shared memory
        try:
            from agent_memory import (
                get_memory_store, MemoryEntry, MemoryType, MemoryScope
            )
            store = get_memory_store()

            handoff_content = json.dumps({
                "event": "account_graduated",
                "account_id": account_id,
                "customer_id": self.customer_id,
                "activation_score": status.activation_score,
                "milestones_hit": status.milestones_hit,
                "days_in_onboarding": status.current_day,
                "graduated_at": datetime.utcnow().isoformat(),
            })

            store.remember(MemoryEntry(
                memory_type=MemoryType.EPISODIC,
                scope=MemoryScope.SHARED,
                content=handoff_content,
                customer_id=self.customer_id,
                account_id=account_id,
                namespace="customer_intelligence",
                key=f"graduation_{account_id}",
                importance=0.85,
            ))
        except Exception as e:
            logger.warning(f"[OnboardingAgent] Failed to store graduation memory: {e}")

        # Publish graduation event
        try:
            from event_system import get_event_manager, EventType
            event_mgr = get_event_manager()
            if event_mgr and hasattr(EventType, 'ACCOUNT_GRADUATED'):
                event_mgr.publisher.publish(
                    EventType.ACCOUNT_GRADUATED,
                    customer_id=self.customer_id,
                    data={
                        "account_id": account_id,
                        "activation_score": status.activation_score,
                        "milestones_hit": status.milestones_hit,
                        "days_in_onboarding": status.current_day,
                    },
                )
        except Exception as e:
            logger.warning(f"[OnboardingAgent] Failed to publish graduation event: {e}")

        return {
            "status": "graduated",
            "account_id": account_id,
            "activation_score": status.activation_score,
            "milestones_hit": status.milestones_hit,
            "days_in_onboarding": status.current_day,
            "message": f"Account {account_id} graduated to steady-state monitoring. "
                       f"Signal Analyst will now handle ongoing analysis.",
        }

    # ────────────────────────────────────────────────────────
    #  Get stored activation plan
    # ────────────────────────────────────────────────────────

    def get_activation_plan(self) -> Optional[Dict[str, Any]]:
        """Retrieve the stored activation plan from memory."""
        try:
            from agent_memory import get_memory_store
            store = get_memory_store()
            memories = store.recall(
                customer_id=self.customer_id,
                namespace="activation_plan",
                limit=1,
            )
            if memories:
                return json.loads(memories[0].content)
        except Exception as e:
            logger.warning(f"[OnboardingAgent] Failed to retrieve plan: {e}")
        return None


# ============================================================
# SERIALISATION HELPERS
# ============================================================

def activation_plan_to_dict(plan: ActivationPlan) -> Dict:
    """Serialise an ActivationPlan for API response."""
    return {
        "customer_id": plan.customer_id,
        "customer_name": plan.customer_name,
        "industry": plan.industry,
        "total_accounts": plan.total_accounts,
        "plan_entries": [asdict(e) for e in plan.plan_entries],
        "global_recommendations": plan.global_recommendations,
        "ttfv_baseline": plan.ttfv_baseline,
        "created_at": plan.created_at,
        "provider_used": plan.provider_used,
        "generation_ms": plan.generation_ms,
    }


def ttfv_status_to_dict(status: TTFVStatus) -> Dict:
    """Serialise TTFVStatus for API response."""
    return asdict(status)
