#!/usr/bin/env python3
"""
Context Graph End-to-End Test
=============================
Tests the full pipeline through the platform APIs:
  1. Create customer via /api/onboarding/complete (10 accounts, 15 KPIs)
  2. Generate context graph 9 CSVs from story arc manifest
  3. Upload 9 CSVs via /api/onboarding/upload
  4. Enable context_graph feature toggle in DB
  5. Run /api/onboarding/process-data (triggers context graph ingestion)
  6. Verify context_nodes and context_edges have data
  7. Save all CSVs and results to output directory

Usage:
    cd kpi-dashboard/backend
    python3 tests/test_context_graph_e2e.py

Output goes to: tests/context-graph-test-out/
"""

import csv
import io
import json
import os
import sys
import time
import requests
from datetime import datetime
from pathlib import Path

# ── Config ──
BASE_URL = "http://localhost:5059"
OUTPUT_DIR = Path(__file__).parent / "context-graph-test-out"
ARC_ID = "arc_expansion_champion"
NUM_ACCOUNTS = 10
NUM_KPIS = 15  # max KPIs to enable
SEED = 42

# Add backend to path
BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))

def log(msg):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {msg}")

def api_get(endpoint, **kwargs):
    r = requests.get(f"{BASE_URL}{endpoint}", **kwargs)
    return r.json() if r.ok else {"_error": r.status_code, "_body": r.text[:300]}

def api_post(endpoint, data=None, **kwargs):
    r = requests.post(f"{BASE_URL}{endpoint}", json=data, **kwargs)
    return r.status_code, (r.json() if r.content else {})

def api_upload(endpoint, files, data):
    r = requests.post(f"{BASE_URL}{endpoint}", files=files, data=data)
    return r.status_code, (r.json() if r.content else {})

def save_json(name, obj):
    path = OUTPUT_DIR / name
    with open(path, "w") as f:
        json.dump(obj, f, indent=2, default=str)
    log(f"  Saved {path.name} ({path.stat().st_size:,} bytes)")

def save_csv_content(name, content):
    path = OUTPUT_DIR / name
    path.write_text(content)
    lines = content.strip().count("\n")
    log(f"  Saved {path.name} ({lines} rows)")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    results = {"test": "context_graph_e2e", "started_at": datetime.now().isoformat(), "steps": {}}

    # ================================================================
    # Step 0: Health check
    # ================================================================
    log("=" * 60)
    log("Context Graph E2E Test")
    log("=" * 60)

    health = api_get("/api/health")
    if health.get("status") != "healthy":
        log(f"FAIL: Server not healthy: {health}")
        return
    log(f"Server: {health.get('version')} — healthy")

    # ================================================================
    # Step 1: Create customer via onboarding/complete
    # ================================================================
    log("\n--- Step 1: Create Customer (10 accounts, 15 KPIs) ---")

    # First, pick 15 KPIs from catalog
    from utils.vertical_registry import get_kpis
    all_kpi_codes = list(get_kpis('dc2_s').keys())
    selected_kpis = all_kpi_codes[:NUM_KPIS]
    log(f"  Selected {len(selected_kpis)} KPIs: {selected_kpis}")

    company_name = f"ContextGraph-Test-{datetime.now().strftime('%m%d-%H%M')}"
    onboarding_payload = {
        "customer_name": company_name,
        "industry": "Technology",
        "num_accounts": NUM_ACCOUNTS,
        "onboarding_mode": "demo",
        "enabled_kpis": selected_kpis,
    }

    status, resp = api_post("/api/onboarding/complete", onboarding_payload)
    log(f"  /api/onboarding/complete → {status}")
    results["steps"]["1_create_customer"] = {"status": status, "response": resp}

    customer_id = resp.get("customer_id")
    if not customer_id:
        log(f"  FAIL: No customer_id in response: {resp}")
        save_json("test_results.json", results)
        return
    log(f"  Customer ID: {customer_id}, Name: {company_name}")
    results["customer_id"] = customer_id
    results["company_name"] = company_name

    # ================================================================
    # Step 2: Generate data — regular 6 CSVs + context graph 9 CSVs
    # ================================================================
    log("\n--- Step 2: Generate CSV Data ---")

    # 2a: Regular CSVs are already generated by /complete. Let's also generate
    #     and save context graph 9 CSVs from the story arc.
    from scripts.generate_context_graph_data import ContextGraphGenerator

    gen = ContextGraphGenerator(
        customer_id=customer_id,
        arc_id=ARC_ID,
        num_accounts=NUM_ACCOUNTS,
        seed=SEED,
    )

    cg_csvs = {
        "stakeholders": gen.generate_stakeholders_csv(),
        "engagement_events": gen.generate_engagement_events_csv(),
        "account_business_profiles": gen.generate_account_business_profiles_csv(),
        "decisions": gen.generate_decisions_csv(),
        "outcomes": gen.generate_outcomes_csv(),
        "signal_edges": gen.generate_signal_edges_csv(),
        "decision_evidence": gen.generate_decision_evidence_csv(),
        "industry_benchmarks": gen.generate_industry_benchmarks_csv(),
        "enhanced_signals": gen.generate_enhanced_signals_csv(),
    }

    log(f"  Generated {len(cg_csvs)} context graph CSVs from arc: {ARC_ID}")

    # Save all context graph CSVs to output dir
    cg_out_dir = OUTPUT_DIR / "context_graph_csvs"
    cg_out_dir.mkdir(parents=True, exist_ok=True)
    file_type_to_filename = {
        "stakeholders": "stakeholders.csv",
        "engagement_events": "engagement_events.csv",
        "account_business_profiles": "account_business_profiles.csv",
        "decisions": "decisions.csv",
        "outcomes": "outcomes.csv",
        "signal_edges": "signal_edges.csv",
        "decision_evidence": "decision_evidence.csv",
        "industry_benchmarks": "industry_benchmarks.csv",
        "enhanced_signals": "enhanced_qualitative_signals.csv",
    }

    csv_stats = {}
    for ft, content in cg_csvs.items():
        fname = file_type_to_filename[ft]
        (cg_out_dir / fname).write_text(content)
        row_count = content.strip().count("\n")
        csv_stats[ft] = {"filename": fname, "rows": row_count, "bytes": len(content)}
        log(f"    {fname}: {row_count} rows")

    results["steps"]["2_generate_csvs"] = {
        "arc_id": ARC_ID,
        "files_generated": len(cg_csvs),
        "csv_stats": csv_stats,
    }

    # Also save any regular CSVs that exist in the customer directory
    customer_data_dir = BACKEND_DIR / "verticals" / f"customer{customer_id}-dc2_s" / "data"
    regular_out_dir = OUTPUT_DIR / "regular_csvs"
    regular_out_dir.mkdir(parents=True, exist_ok=True)
    if customer_data_dir.exists():
        for csv_file in customer_data_dir.glob("*.csv"):
            import shutil
            dest = regular_out_dir / csv_file.name
            shutil.copy2(csv_file, dest)
            row_count = sum(1 for _ in open(csv_file)) - 1
            log(f"    (regular) {csv_file.name}: {row_count} rows")
    else:
        log(f"  Note: customer data dir not yet created: {customer_data_dir}")

    # ================================================================
    # Step 3: Upload 9 context graph CSVs via /api/onboarding/upload
    # ================================================================
    log("\n--- Step 3: Upload Context Graph CSVs ---")

    upload_results = {}
    for ft, content in cg_csvs.items():
        fname = file_type_to_filename[ft]
        files = {"file": (fname, content, "text/csv")}
        data = {"customer_id": customer_id, "file_type": ft}
        status, resp = api_upload("/api/onboarding/upload", files=files, data=data)
        ok = status == 200 and resp.get("status") == "success"
        upload_results[ft] = {"status": status, "ok": ok, "response": resp}
        log(f"  {ft}: {'OK' if ok else 'FAIL'} (HTTP {status})")
        if not ok:
            log(f"    Response: {json.dumps(resp)[:200]}")

    results["steps"]["3_upload_csvs"] = upload_results
    upload_success_count = sum(1 for v in upload_results.values() if v.get("ok"))
    log(f"  Uploaded: {upload_success_count}/{len(cg_csvs)} files")

    # ================================================================
    # Step 4: Enable context_graph feature toggle
    # ================================================================
    log("\n--- Step 4: Enable context_graph Feature Toggle ---")

    from dotenv import load_dotenv
    load_dotenv()
    from sqlalchemy import create_engine, text
    engine = create_engine(os.getenv("DATABASE_URL"))

    with engine.begin() as conn:
        # Check if toggle already exists
        existing = conn.execute(text(
            "SELECT id FROM feature_toggles WHERE customer_id = :cid AND feature_name = 'context_graph'"
        ), {"cid": customer_id}).scalar()

        if existing:
            conn.execute(text(
                "UPDATE feature_toggles SET enabled = true WHERE id = :id"
            ), {"id": existing})
            log(f"  Updated existing toggle (id={existing}) → enabled=true")
        else:
            conn.execute(text("""
                INSERT INTO feature_toggles (customer_id, feature_name, enabled, config, description)
                VALUES (:cid, 'context_graph', true, :cfg, 'Context graph for E2E test')
            """), {
                "cid": customer_id,
                "cfg": json.dumps({
                    "story_arcs": True,
                    "signal_edges": True,
                    "stakeholder_tracking": True,
                    "decision_lifecycle": True,
                    "outcome_economics": True,
                    "industry_benchmarks": True,
                }),
            })
            log("  Inserted context_graph toggle → enabled=true (all sub-toggles ON)")

    # Also need to enable the global CONTEXT_GRAPH toggle
    # This is in-memory in feature_toggles.py; we need it enabled for the API call
    try:
        from feature_toggles import feature_toggles, FeatureToggle
        feature_toggles.enable(FeatureToggle.CONTEXT_GRAPH)
        log("  Global CONTEXT_GRAPH toggle → enabled")
    except Exception as e:
        log(f"  Warning: Could not enable global toggle: {e}")

    results["steps"]["4_feature_toggle"] = {"customer_id": customer_id, "enabled": True}

    # ================================================================
    # Step 5: Process data (triggers context graph ingestion)
    # ================================================================
    log("\n--- Step 5: Process Data (includes context graph ingestion) ---")

    process_payload = {
        "customer_id": customer_id,
        "skip_wizard_b": True,
        "skip_wizard_c": True,
        "strict_kpi_ranges": False,
    }

    t0 = time.time()
    status, resp = api_post("/api/onboarding/process-data", process_payload, timeout=300)
    duration = time.time() - t0

    log(f"  /api/onboarding/process-data → {status} ({duration:.1f}s)")
    steps_completed = resp.get("steps_completed", [])
    log(f"  Steps completed: {steps_completed}")
    cg_result = resp.get("context_graph", {})
    if cg_result:
        log(f"  Context graph: {cg_result.get('nodes_inserted', 0)} nodes, "
            f"{cg_result.get('edges_inserted', 0)} edges, "
            f"files: {cg_result.get('files_loaded', [])}")
    proc_errors = resp.get("errors", [])
    if proc_errors:
        log(f"  Warnings: {proc_errors}")

    results["steps"]["5_process_data"] = {
        "http_status": status,
        "duration_s": round(duration, 2),
        "steps_completed": steps_completed,
        "context_graph": cg_result,
        "errors": proc_errors,
        "response": resp,
    }

    # ================================================================
    # Step 6: Verify context graph data in DB
    # ================================================================
    log("\n--- Step 6: Verify Context Graph Data in DB ---")

    verification = {}
    with engine.connect() as conn:
        # Count nodes by type
        node_counts = conn.execute(text("""
            SELECT node_type, COUNT(*) as cnt
            FROM context_nodes
            WHERE customer_id = :cid
            GROUP BY node_type
            ORDER BY node_type
        """), {"cid": customer_id}).fetchall()

        total_nodes = 0
        for row in node_counts:
            ntype, cnt = row[0], row[1]
            verification[f"nodes_{ntype}"] = cnt
            total_nodes += cnt
            log(f"  Nodes [{ntype}]: {cnt}")

        verification["total_nodes"] = total_nodes
        log(f"  Total nodes: {total_nodes}")

        # Count edges by type
        edge_counts = conn.execute(text("""
            SELECT edge_type, COUNT(*) as cnt
            FROM context_edges
            WHERE customer_id = :cid
            GROUP BY edge_type
            ORDER BY edge_type
        """), {"cid": customer_id}).fetchall()

        total_edges = 0
        for row in edge_counts:
            etype, cnt = row[0], row[1]
            verification[f"edges_{etype}"] = cnt
            total_edges += cnt
            log(f"  Edges [{etype}]: {cnt}")

        verification["total_edges"] = total_edges
        log(f"  Total edges: {total_edges}")

        # Sample nodes
        sample_nodes = conn.execute(text("""
            SELECT node_id, node_type, node_subtype, label, revenue_impact
            FROM context_nodes
            WHERE customer_id = :cid
            ORDER BY node_id
            LIMIT 10
        """), {"cid": customer_id}).fetchall()

        sample_data = []
        for row in sample_nodes:
            sample_data.append({
                "node_id": row[0], "type": row[1], "subtype": row[2],
                "label": row[3][:60] if row[3] else "", "revenue_impact": float(row[4]) if row[4] else None
            })
        verification["sample_nodes"] = sample_data

        # Revenue at risk summary
        rev_summary = conn.execute(text("""
            SELECT revenue_impact_type, COUNT(*), SUM(COALESCE(revenue_impact, 0))
            FROM context_nodes
            WHERE customer_id = :cid AND revenue_impact IS NOT NULL
            GROUP BY revenue_impact_type
        """), {"cid": customer_id}).fetchall()

        rev_data = {}
        for row in rev_summary:
            rev_data[row[0] or "untyped"] = {"count": row[1], "total_impact": float(row[2])}
        verification["revenue_summary"] = rev_data
        if rev_data:
            log(f"  Revenue impact summary:")
            for rtype, rinfo in rev_data.items():
                log(f"    {rtype}: {rinfo['count']} nodes, ${rinfo['total_impact']:,.0f}")

    results["steps"]["6_verification"] = verification

    # ================================================================
    # Step 7: Summary
    # ================================================================
    log("\n" + "=" * 60)
    all_ok = (
        upload_success_count == len(cg_csvs) and
        total_nodes > 0
    )
    if all_ok:
        log("PASS: Context Graph E2E Test")
    else:
        log("PARTIAL: Some steps had issues")

    results["completed_at"] = datetime.now().isoformat()
    results["overall_status"] = "PASS" if all_ok else "PARTIAL"
    results["summary"] = {
        "customer_id": customer_id,
        "company_name": company_name,
        "arc_id": ARC_ID,
        "accounts": NUM_ACCOUNTS,
        "kpis": NUM_KPIS,
        "csvs_uploaded": f"{upload_success_count}/{len(cg_csvs)}",
        "nodes_inserted": total_nodes,
        "edges_inserted": total_edges,
        "process_data_duration_s": round(duration, 2),
    }

    save_json("test_results.json", results)
    log(f"\nAll output saved to: {OUTPUT_DIR}")
    log(f"Customer {customer_id} preserved for incremental update testing.")
    log("=" * 60)


if __name__ == "__main__":
    main()
