#!/usr/bin/env python3
"""G1.5 — Panel Quality Report runner.

Reads the panel for the requested customer ids, runs the quality checks
defined in `panel.panel_quality_report`, and renders a markdown artifact
for reviewer (Manoj) at the G1.5 gate.

Usage (from kpi-dashboard/backend):
    PYTHONPATH=. python predictor/scripts/g15_panel_quality.py 393
    PYTHONPATH=. python predictor/scripts/g15_panel_quality.py 393 491
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine

# Make the package importable when run as a script
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from predictor.panel import build_panel, panel_quality_report  # noqa: E402


def render_markdown(report: dict, customer_ids: list, panel_df: pd.DataFrame) -> str:
    """Render the quality report as a markdown G1.5 deliverable."""
    ts = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    status_emoji = {
        'OK': 'PASS',
        'HARD_FAIL': 'HARD FAIL',
        'EMPTY': 'EMPTY PANEL',
    }.get(report['status'], report['status'])

    lines = [
        f'# G1.5 — Panel Quality Report',
        f'',
        f'- **Generated:** {ts}',
        f'- **Customer IDs scoped:** {customer_ids}',
        f'- **Status:** **{status_emoji}**',
        f'',
    ]

    if report['status'] == 'EMPTY':
        lines.append(f'> {report["message"]}')
        return '\n'.join(lines)

    lines.extend([
        f'## Summary',
        f'',
        f'| | Value |',
        f'|---|---|',
        f'| Total panel rows | {report["total_rows"]} |',
        f'| Tenants | {report["tenants"]} |',
        f'| Accounts | {report["accounts"]} |',
        f'| Months observed per account — min | {report["months_observed_per_account"]["min"]} |',
        f'| Months observed per account — p50 | {report["months_observed_per_account"]["p50"]} |',
        f'| Months observed per account — mean | {report["months_observed_per_account"]["mean"]:.2f} |',
        f'| Months observed per account — max | {report["months_observed_per_account"]["max"]} |',
        f'',
        f'## Segment × Tenant Cardinality',
        f'',
        f'| Tenant / Segment | Accounts |',
        f'|---|---|',
    ])
    for key, n in sorted(report['segment_x_tenant_counts'].items()):
        lines.append(f'| `{key}` | {n} |')

    lines.extend([
        f'',
        f'## Outcome Event Counts (per tenant, total over panel)',
        f'',
        f'| Event | Per-tenant counts |',
        f'|---|---|',
    ])
    for evt, counts in report['outcome_event_counts'].items():
        formatted = ', '.join(f'{tid}:{n}' for tid, n in sorted(counts.items()))
        lines.append(f'| `{evt}` | {formatted or "—"} |')

    if report['flags']:
        lines.extend([f'', f'## Flags', f''])
        for flag in report['flags']:
            sev_label = '**HARD FAIL**' if flag['severity'] == 'hard_fail' else 'WARN'
            lines.append(f'### {sev_label}: `{flag["type"]}`')
            lines.append(f'')
            lines.append(f'> {flag["detail"]}')
            lines.append(f'')
            lines.append(f'```json')
            lines.append(json.dumps(
                {k: v for k, v in flag.items() if k not in ('type', 'severity', 'detail')},
                indent=2, default=str
            ))
            lines.append(f'```')
            lines.append(f'')
    else:
        lines.extend([f'', f'## Flags', f'', f'No issues — clean panel for the scoped tenants.', f''])

    # Panel head sample
    lines.extend([
        f'## Panel Sample (first 10 rows)',
        f'',
        f'```',
        panel_df.head(10).to_string(index=False),
        f'```',
        f'',
        f'---',
        f'*Generated by `predictor/scripts/g15_panel_quality.py`. ',
        f'Source SQL: `predictor/sql/build_panel.sql`.*',
    ])

    return '\n'.join(lines)


def main() -> int:
    if len(sys.argv) < 2:
        print('Usage: g15_panel_quality.py <customer_id> [<customer_id> ...]')
        return 2

    customer_ids = [int(x) for x in sys.argv[1:]]
    db_url = os.environ.get(
        'DATABASE_URL',
        'postgresql://cspulse:cspulse@localhost:5433/cs_pulse',
    )
    engine = create_engine(db_url)

    df = build_panel(customer_ids=customer_ids, engine=engine)
    report = panel_quality_report(df)
    md = render_markdown(report, customer_ids, df)

    # Write artifact for the gate review
    out_dir = Path(__file__).resolve().parent.parent / 'sql'
    suffix = '_'.join(str(x) for x in customer_ids)
    out_path = out_dir / f'g15_panel_quality_report__cust_{suffix}.md'
    out_path.write_text(md)

    print(md)
    print(f'\n[Saved to {out_path}]')
    return 0 if report['status'] != 'HARD_FAIL' else 1


if __name__ == '__main__':
    sys.exit(main())
